# Generated by Django 4.1.7 on 2023-06-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user_login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("number", models.BigIntegerField(max_length=10)),
                ("password", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "crud",
            },
        ),
    ]
